[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "HTCV_DeeplabV3_v1"
version = "0.0.1"
authors = [
  { name="Haaroon Afroz", email="haaroon.afroz.ognawala@uni-weimar.de" },
]
description = "First attempt at using DeeplabV3 CNN architecture for semantic material segmentation"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pytest", "torch", "tqdm", "matplotlib", "torchvision", "scikit-learn", "seaborn", "pyyaml", "yacs"
]
