DATA:
  DATASET: 'VOCSegmentation'
  ROOT: './data'

MODEL:
  NUM_CLASSES: 21

MISC:
  RUN_NAME: 'PASCALVOC_Epoch30'
  RESULTS_CSV: './results'
  SAVE_MODEL_PATH: './saved_models'
  PRETRAINED_WEIGHTS: './saved_models/PASCALVOC_Epoch20.pth'
  NO_CUDA: False

TRAIN:
  BASE_LR: 0.0001
  MILESTONES: [10, 20]
  GAMMA: 0.1
  BATCH_SIZE: 8
  NUM_EPOCHS: 10
  EARLY_STOPPING: False

AUGMENTATION:
  HORIZONTAL_FLIP_PROB: 0.5
  ROTATION_DEGREES: 10