DATA:
  DATASET: 'VOCSegmentation'
  ROOT: '/kaggle/input/vocsegmentation-2012/VOCdevkit/VOC2012' # './data/VOCdevkit/VOC2012'

MODEL:
  NUM_CLASSES: 21

MISC:
  RUN_NAME: 'PASCALVOC_config1_run'
  RESULTS_CSV: '/kaggle/working/repository_content/results'
  SAVE_MODEL_PATH: '/kaggle/working/repository_content/saved_models'
  PRETRAINED_WEIGHTS: ''
  NO_CUDA: False

TRAIN:
  BASE_LR: 0.001
  MILESTONES: [10, 20]
  GAMMA: 0.1
  BATCH_SIZE: 16
  NUM_EPOCHS: 3
  EARLY_STOPPING: False

AUGMENTATION:
  HORIZONTAL_FLIP_PROB: 0.5
  ROTATION_DEGREES: 10