DATA:
  DATASET: 'VOCSegmentation'
  ROOT: './data/VOCdevkit/VOC2012'

MODEL:
  NUM_CLASSES: 21

MISC:
  RUN_NAME: 'PASCALVOC_config1_run'
  RESULTS_CSV: './results'
  SAVE_MODEL_PATH: './saved_models'
  PRETRAINED_WEIGHTS: '' #'COCO_WITH_VOC_LABELS_V1'
  NO_CUDA: False

TRAIN:
  BASE_LR: 0.0001
  MILESTONES: [10, 20]
  GAMMA: 0.1
  BATCH_SIZE: 8
  NUM_EPOCHS: 100
  EARLY_STOPPING: False

AUGMENTATION:
  HORIZONTAL_FLIP_PROB: 0.5
  ROTATION_DEGREES: 10