DATA:
  DATASET: 'VOCSegmentation'
  VOC_ROOT: '/kaggle/input/vocsegmentation-2012'
  MATERIAL_ROOT: '/kaggle/input/material-dataset/material_dataset'

MODEL:
  NUM_CLASSES_OBJECT: 21
  NUM_CLASSES_MATERIAL: 4

MISC:
  RUN_NAME: 'DeeplabV3Plus_KaggleRun'
  RESULTS_CSV: '/kaggle/working/repository_content/results'
  SAVE_MODEL_PATH: '/kaggle/working/repository_content/saved_models'
  PRETRAINED_WEIGHTS: '' #'./saved_models/best_deeplabv3plus_resnet101_voc_os16.pth' # './saved_models/PASCALVOC_Epoch5-1.pth'
  NO_CUDA: False

TRAIN:
  BASE_LR: 0.0005
  MILESTONES: [10, 20]
  GAMMA: 0.1
  BATCH_SIZE: 8
  NUM_EPOCHS: 1
  EARLY_STOPPING: False

AUGMENTATION:
  HORIZONTAL_FLIP_PROB: 0.5
  ROTATION_DEGREES: 10