DATA:
  DATASET: 'Material Dataset'
  MATERIAL_ROOT: './data/material_dataset'

MODEL:
  NUM_CLASSES_MATERIAL: 5
  BACKBONE: 'mobilenet'
  MODEL: 'Deeplabv3Plus'   # 'U-Net'

MISC:
  RUN_NAME: 'U-Net_TestRun'
  RESULTS_CSV: './results'
  SAVE_MODEL_PATH: './saved_models'
  PRETRAINED_WEIGHTS: '.\saved_models\Semantic_Segmentation_100Epochs_Unet.pth'
  SAVE_PREDICTION: './predictions'
  NO_CUDA: False

TRAIN:
  BASE_LR: 0.0001
  MILESTONES: [10, 20]
  GAMMA: 0.1
  BATCH_SIZE: 4
  NUM_EPOCHS: 1
  EARLY_STOPPING: False

AUGMENTATION:
  HORIZONTAL_FLIP_PROB: 0.5
  ROTATION_DEGREES: 10
  CROP_SIZE: [256,256]